### PR TITLE
Fix 1.81 lints (extra reference and never type fallback)

### PR DESCRIPTION
**Pull request by strohel**
### Fix `dependency_on_unit_never_type_fallback` lint

This relates to
- rust-lang/rust#123748
- https://doc.rust-lang.org/nightly/edition-guide/rust-2024/never-type-fallback.html

And frankly I still don't really understand why never type was involved in our code in the first place.

### CODE REVIEW

**Review by goodhoko — APPROVED** [review]

**Comment by strohel** [comment]
@mbernat @goodhoko I had to push more changes for this to actually fix CI, PTAL. CC @bschwind.

**Comment by strohel** [comment]
The Docker CI is still broken, I'll take a look in a separate PR.

**Review by goodhoko — APPROVED** [review]
stil LGTM

**Comment by mbernat** [comment]
LGTM as well

**Pull request merged**
