### PR TITLE
server: Implement disable-peer and enable-peer commands

### PR DESCRIPTION
**Pull request by networkException**
This pull request implements enabling and disabling of peers directly accessing the server's database, as such not requiring non server admin peers.

The server will also apply changes to the wireguard interface immediately

### CODE REVIEW

**Comment by networkException** [comment]
Should the client api perhaps also react to enable or disable immediately? Currently there's no specialized endpoint and I also don't know all implications of informing wireguard of every chance to a peer using `PUT /admin/peers/{id}`.

**Comment by mcginty** [comment]
Thanks! This seems good to have. I'll merge this and refactor stuff a little bit :).

**Comment by networkException** [comment]
Fixed the formatting in the latest commit

**Comment by mcginty** [comment]
Great, thanks! Apologies for the delay in reviewing, been on a roadtrip with limited connectivity.

**Comment by networkException** [comment]
No problem, hope you enjoyed your roadtrip :smile:

**Pull request merged**
