### PR TITLE
Update netlink-packet-route to 0.21

### PR DESCRIPTION
**Pull request by odrling**
Fixes: https://github.com/tonarino/innernet/issues/303

### CODE REVIEW

**Comment by strohel** [comment]
Oh, thanks for the PR, @odrling! I quickly skimmed the code and it looked good, but also flagging @bschwind for review.

I've triggered CI run and it surfaced a (boring) clippy + rustfmt lints, could you please fix them? :pray:

**Comment by odrling** [comment]
> I've triggered CI run and it surfaced a (boring) clippy + rustfmt lints, could you please fix them? 🙏

My bad, should be fixed now, the checks pass when I run them locally.

**Review by bschwind — APPROVED** [review]
Nice work! The resulting code from the dependency update is a lot cleaner.

**Review by strohel — APPROVED** [review]
Had a more thorough look, this is indeed more type-safe thanks to the new API, nice! Thanks for the much-needed work, @odrling.

I'll go ahead and merge.

**Pull request merged**
