### PR TITLE
fix nightly build

### PR DESCRIPTION
**Pull request by sabify**
Related:  https://github.com/tkaitchuck/aHash/issues/200, https://github.com/dalek-cryptography/curve25519-dalek/issues/631

### CODE REVIEW

**Review by mcginty — APPROVED** [review]
Looks good to me!

**Review by bschwind — APPROVED** [review]
Looks good to me as well, let's see if we can get CI to cooperate.

**Comment by sabify** [comment]
Those Clippy errors were not related to this PR, but I tried to fix them.

**Comment by skywhale** [comment]
Let me go ahead and merge this 🙏

**Pull request merged**
